platform :ios

#pod 'SVPullToRefresh',     '~> 0.3'
pod 'iCarousel',           '~> 1.7.2'
pod 'HPGrowingTextView',   '~> 0.0.1'
#pod 'NSLogger',            '~> 1.1' 
pod 'PrettyKit',           '~> 0.2.0'
#pod 'DTCoreText',          '~> 1.0.2'
pod 'NYXImagesKit',        '~> 2.1.2'
pod 'TTTAttributedLabel',  '~> 1.4.0'
pod 'DCRoundSwitch',       '~> 0.0.1'
pod 'AFNetworking',        '~> 0.10.1'
pod 'SDWebImage',          '~> 2.7'
#pod 'DCKeyValueObjectMapping', '~> 1.1'
#pod 'BlockAlertsAnd-ActionSheets', '~> 1.0.0'
pod 'SSKeychain',          '~> 0.1.4'
pod 'UIWebViewRemoveShadow','~> 0.0.1'
pod 'MBProgressHUD',       '~> 0.5' 
pod 'UIAlertView-Blocks',  '~> 0.0.1'
pod 'Reachability',        '~> 3.1.0'
pod 'DDURLParser',         '~> 0.0.1'
pod 'ActionSheetPicker',   '~> 0.0.1'
pod 'KKGridView',          '~> 0.6.8.2'
